FROM node:lts-alpine AS build

RUN mkdir -p /app

WORKDIR /app

COPY package.json ./

RUN yarn

COPY . ./

RUN yarn build

FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /var/www/html/

EXPOSE 80

ENTRYPOINT ["nginx","-g","daemon off;"]
