FROM node:lts-alpine AS build

RUN mkdir -p /app

# Define build arguments for environment variables
ARG VITE_BASE_API_URL=https://api.weight-tracker.zirr.dev/api/v1

# Set environment variables during the build process
ENV VITE_BASE_API_URL=$VITE_BASE_API_URL

WORKDIR /app

COPY package.json ./

RUN yarn

COPY . ./

RUN yarn build

FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /var/www/html/

EXPOSE 80

ENTRYPOINT ["nginx","-g","daemon off;"]
